modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "MIT"
issueTrackerURL = "${mod_github}/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''
logoFile = "assets/${mod_id}/logo.png"
displayURL = "${mod_github}"

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "modern_industrialization"
type = "required"
versionRange = "${modern_industrialization_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "emi"
type = "optional"
versionRange = "${emi_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "tesseract_api"
type = "required"
versionRange = "${tesseract_version_range}"
ordering = "AFTER"
side = "BOTH"